### ISSUE TITLE
Add tests and/or testdata

### ISSUE THREAD

**Issue by DGuidi** [liberostelios/NetTopologySuite.IO.Dwg#1]
Please add, if possible, testcases with testdata, so we can made some experiments.

**Comment by liberostelios** [comment]
Just pushed a demo project and a test drawing. You will need AutoCAD Map 2012 (or later) to run the test.

I am quite new at this so let me know if there is anything i am missing and i should do better.

**Comment by DGuidi** [comment]
thanks, hope to take a look although I don't have AutoCAD :(
